# Generated by Django 2.0 on 2017-12-16 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='下载链接')),
            ],
            options={
                'verbose_name_plural': '公文文件',
                'verbose_name': '公文文件',
            },
        ),
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_created=True, verbose_name='发文时间')),
                ('ori_type', models.CharField(choices=[('教务', '教学教务'), ('学术', '学术科研'), ('行政', '行政通知'), ('学工', '学生工作'), ('校园', '校园生活')], max_length=4, verbose_name='原始类别')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(max_length=2000, verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '公文',
                'verbose_name': '公文',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isTop', models.BooleanField(default=False, verbose_name='置顶')),
                ('isShow', models.BooleanField(default=False, verbose_name='继续展示')),
                ('click', models.IntegerField(default=0, verbose_name='点击量')),
                ('approve', models.IntegerField(default=0, verbose_name='点赞量')),
                ('announce', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Announce')),
            ],
            options={
                'verbose_name_plural': '已展示公文',
                'verbose_name': '已展示公文',
            },
        ),
        migrations.CreateModel(
            name='SType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='类名')),
            ],
            options={
                'verbose_name_plural': '小类',
                'verbose_name': '小类',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='单位名')),
                ('perm', models.IntegerField(verbose_name='权限等级')),
            ],
            options={
                'verbose_name_plural': '单位',
                'verbose_name': '单位',
            },
        ),
        migrations.AddField(
            model_name='announce',
            name='s_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SType'),
        ),
        migrations.AddField(
            model_name='announce',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Unit'),
        ),
        migrations.AddField(
            model_name='afile',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Announce'),
        ),
    ]
