# Generated by Django 2.0 on 2017-12-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171216_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='user',
            field=models.CharField(max_length=50, null=True, verbose_name='英文名'),
        ),
    ]
